const locationData = {
  "Coral Bay": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/603-coral-bay_orig.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
    "description": "Welcome to Coral Bay, a breathtaking coastal gem nestled on the southwest shores of Cyprus, where azure waters meet golden sands, creating a picturesque haven for visitors seeking sun-soaked bliss. Renowned for its pristine beaches, Coral Bay beckons with its inviting Mediterranean charm and a laid-back atmosphere. The main beach, with its Blue Flag status, boasts soft, golden sands lapped by crystal-clear waters, making it an ideal spot for sunbathing, swimming, and water sports enthusiasts alike. The surrounding landscape, adorned with rugged cliffs and verdant hills, provides a stunning backdrop for unforgettable sunsets. Beyond the beach, Coral Bay offers a vibrant array of waterfront restaurants, serving delectable local cuisine and fresh seafood, allowing visitors to savour the flavours of Cyprus while enjoying panoramic views of the sea. For those seeking adventure, the nearby Akamas Peninsula unfolds its natural wonders, inviting exploration through hiking trails and boat excursions. Coral Bay seamlessly blends natural beauty with modern amenities, ensuring an idyllic retreat for travellers seeking tranquillity and the warmth of Cypriot hospitality. Whether you're basking in the sun, exploring nature trails, or indulging in local delicacies, Coral Bay promises a memorable escape along the sun-kissed shores of Cyprus."
  },
  "Argaka": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/611-argaka_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
    "description": "Welcome to Argaka, a picturesque and enchanting destination nestled on the western coast of Cyprus, within the captivating region of Paphos. As you step into this coastal haven, you'll find yourself surrounded by a harmonious blend of azure Mediterranean waters, golden sandy beaches, and lush green landscapes. Argaka exudes a sense of tranquillity and authenticity, making it an ideal retreat for those seeking a peaceful escape. The village itself is a charming mosaic of traditional Cypriot architecture, with whitewashed buildings adorned with vibrant bougainvillaea and narrow winding streets that invite exploration. Nature enthusiasts will be delighted by the proximity to the Akamas Peninsula, a pristine wilderness where rugged cliffs, hidden coves, and fragrant pine forests create an idyllic backdrop for hiking and exploration. Argaka is also renowned for its citrus orchards and olive groves, offering visitors a taste of the region's rich agricultural heritage. Local tavernas beckon with the promise of authentic Cypriot cuisine, where you can savour freshly caught seafood and indulge in the warmth of traditional hospitality. Whether you're drawn to the tranquil beaches, the cultural richness, or the natural wonders that surround it, Argaka invites you to experience the timeless charm of Cyprus in all its glory."
  },
  "Aphrodite Hills": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/931-aphrodite-hills_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
    "description": "Welcome to Aphrodite Hills, a captivating and enchanting destination nestled on the sun-kissed shores of Cyprus. This idyllic area, named after the ancient Greek goddess of love and beauty, Aphrodite, offers a harmonious blend of rich history, stunning natural beauty, and modern luxury. Aphrodite Hills is renowned for its world-class golf course, providing enthusiasts with a challenging and scenic backdrop for their favourite pastime. As you explore the meticulously landscaped grounds, you'll be greeted by breathtaking views of the Mediterranean Sea, adding a touch of serenity to your golfing experience. The resort itself boasts a range of luxurious accommodations, from elegant villas with private pools to stylish apartments, ensuring a comfortable and indulgent stay. Beyond golf, Aphrodite Hills beckons with its spa and wellness facilities, inviting you to rejuvenate your body and soul amidst the tranquil surroundings. The village square offers a charming array of shops, restaurants, and cafes, creating a vibrant hub for socializing and cultural exploration. For history enthusiasts, nearby archaeological sites such as the Sanctuary of Aphrodite provide a glimpse into the region's rich past. Whether you seek relaxation, recreation, or a taste of Cypriot culture, Aphrodite Hills promises an unforgettable experience that lingers in the heart long after you've bid farewell to this Mediterranean gem."
  },
  "Ayia Thekla": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/970-ayia-thekla_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
    "description": "Welcome to the enchanting coastal region of Ayia Thekla in Cyprus, where azure waters meet golden sands, creating a picturesque haven for travellers seeking tranquillity and natural beauty. Nestled along the southeastern coast of the island, Ayia Thekla is a serene escape just a short drive from the lively city of Ayia Napa. This idyllic coastal enclave is renowned for its pristine beaches, including the famous Nissi Beach, where crystal-clear waters beckon sun-seekers and water enthusiasts alike. Ayia Thekla's charm extends beyond its shoreline, with the iconic Ayia Thekla Chapel standing as a timeless symbol of the area's rich history and cultural significance. Explore the coastal paths that wind through the landscape, providing breathtaking views of the Mediterranean Sea. Nature lovers will appreciate the nearby Cape Greco National Forest Park, a protected area that offers hiking trails and panoramic vistas of the rugged coastline. Whether you're looking to bask in the sun, explore historical sites, or simply unwind amidst stunning surroundings, Ayia Thekla promises an unforgettable experience, combining the best of Cyprus's natural wonders and warm hospitality."


  },
  "Kapparis": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/986-kapparis_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
    "description": "Nestled along the picturesque eastern coast of Cyprus, Kapparis emerges as a hidden gem, offering visitors a serene escape with its laid-back atmosphere and captivating coastal charm. This quaint resort town, situated just a short drive from the bustling city of Protaras, presents a perfect blend of tranquillity and accessibility. Kapparis boasts pristine sandy beaches that stretch lazily along the azure Mediterranean Sea, inviting sunseekers to bask in the warmth of the Cyprus sun. The crystal-clear waters beckon both swimmers and snorkelers, revealing a vibrant underwater world teeming with marine life. Beyond its idyllic beaches, Kapparis unveils a tapestry of local flavours at its charming tavernas and seafood restaurants, where visitors can savour authentic Cypriot cuisine infused with Mediterranean influences. The town's coastal promenade offers a leisurely stroll with panoramic views, while nearby nature trails lead adventurous souls through the rugged beauty of the Cape Greco National Forest Park. Kapparis, with its friendly locals and unhurried pace, provides a perfect retreat for those seeking a relaxing getaway infused with natural beauty, cultural richness, and the warm hospitality that defines the essence of Cyprus."


  },
  "Protaras": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/994-protaras_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Welcome to the idyllic coastal paradise of Protaras in Cyprus, where azure waters meet golden sands, creating a haven for sun-seekers and nature enthusiasts alike. Nestled on the southeastern coast of the island, Protaras beckons with its postcard-perfect beaches, most notably the world-renowned Fig Tree Bay. The crystal-clear waters here are an irresistible invitation to snorkelers and swimmers, while the fine, powdery sand is perfect for leisurely strolls and sunbathing. Beyond the beaches, Protaras boasts a vibrant atmosphere with a bustling town centre lined with charming cafes, restaurants, and shops. Whether you're savouring freshly caught seafood at a seaside taverna or exploring the lively Protaras Strip with its vibrant nightlife, the town offers a delightful blend of relaxation and excitement. Nature lovers will find solace in the nearby Cape Greco National Forest Park, where hiking trails wind through rugged landscapes and panoramic viewpoints provide breathtaking vistas of the Mediterranean. Families will appreciate the myriad of water sports, boat excursions, and the nearby WaterWorld-themed Waterpark, ensuring there's never a dull moment. With its warm hospitality, stunning landscapes, and a perfect blend of leisure and adventure, Protaras stands as a jewel in Cyprus's crown, promising an unforgettable experience for every visitor."

  },
  "Pissouri": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1007-pissouri_orig%20copy%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled between the azure waters of the Mediterranean Sea and the rugged slopes of the Troodos Mountains, Pissouri beckons as a captivating haven on the southwestern coast of Cyprus. Renowned for its picturesque charm and a harmonious blend of traditional Cypriot character with modern amenities, Pissouri unfolds as a multifaceted gem waiting to be discovered. The village, perched on a hillside, offers panoramic views of the surrounding landscape, a breathtaking tapestry of vineyards and olive groves that stretch towards the horizon. Pissouri is a haven for gastronomic enthusiasts, inviting them to savour the delectable flavours of authentic Cypriot cuisine in its quaint tavernas and family-run restaurants. The village square, a hub of local life, exudes a timeless appeal with its stone architecture and vibrant bougainvillaea-lined streets, providing a charming backdrop for leisurely strolls. Adventure enthusiasts are lured by the nearby Blue Flag beach, where the warm Mediterranean waters meet golden sands, creating an idyllic setting for water sports or simply unwinding under the Mediterranean sun. Pissouri seamlessly marries the tranquillity of a traditional village with the allure of a coastal retreat, offering a unique and unforgettable experience for those seeking a slice of authentic Cypriot life."

  },
  "Kato Drys": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1040-kato-drys_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled in the heart of Cyprus, the picturesque village of Kato Drys beckons visitors with its timeless charm and rich cultural tapestry. Steeped in history, this quaint settlement offers a captivating journey into the island's past, showcasing traditional Cypriot life amidst the tranquil embrace of nature. Stroll through narrow cobblestone streets lined with beautifully preserved stone houses adorned with vibrant bougainvillaea, and you'll feel the echoes of centuries gone by. Kato Drys is a haven for those seeking an authentic experience, where the warm hospitality of the locals envelops you like a familiar embrace. The village is renowned for its unique architecture, including the meticulously restored Folk Art Museum, where artefacts and exhibits vividly narrate the region's heritage. As you explore the winding alleys, you'll encounter artisan workshops, where skilled craftsmen practice age-old trades, from weaving intricate lace to crafting traditional pottery. The scent of local delicacies wafts from traditional tavernas, tempting you to savour mouthwatering dishes that pay homage to Cyprus's culinary legacy. Surrounded by undulating vineyards, Kato Drys is also a gateway to the island's burgeoning wine culture. Visitors can indulge in wine tastings at local wineries, immersing themselves in the velvety notes of indigenous grape varieties. For nature enthusiasts, the nearby Machairas Forest provides a serene backdrop for hiking, with trails leading to panoramic viewpoints and hidden waterfalls. Whether you're drawn to the village's historical allure, artistic endeavours, or the simple pleasure of savouring life's culinary and natural delights, Kato Drys is a destination that invites you to step into a bygone era and create lasting memories in the heart of Cyprus."

  },
  "Oroklini": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1053-oroklini_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Beyond the sparkling coastline, Oroklini unveils a rich tapestry of history and tradition. The village boasts a collection of quaint tavernas, where the tantalising aroma of freshly grilled souvlaki mingles with the lively chatter of locals. The historic St. Mamas Church stands as a testament to Oroklini's cultural heritage, offering a serene escape for those seeking a glimpse into the island's past. For nature enthusiasts, the nearby Larnaca Salt Lake becomes a haven for migratory birds, creating a mesmerizing spectacle against the backdrop of the Hala Sultan Tekke mosque. Whether you're a sun seeker, a history buff, or someone craving the unique flavours of Cypriot cuisine, Oroklini promises an unforgettable experience. With its welcoming atmosphere and a harmonious blend of natural beauty and cultural richness, Oroklini emerges as a captivating destination for those in search of a Mediterranean escape."

  },
  "Chloraka": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1054-chloraka_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Boasting a stunning coastline, Chloraka unfolds a mosaic of pristine beaches and crystalline waters that beckon sun-seekers to unwind and rejuvenate. The village is also a treasure trove of historical wonders, with ancient sites like the Agios Georgios Church and the Agios Nikolaos Chapel standing as testaments to its rich past. For those with an appetite for culinary exploration, Chloraka's tavernas and eateries serve up a delectable array of traditional Cypriot dishes, ensuring a flavourful journey through the region's gastronomic heritage. Whether you're drawn to Chloraka for its serene beaches, cultural landmarks, or culinary delights, this charming Cypriot gem promises an enchanting escape that leaves an indelible mark on every visitor. With its blend of authenticity and hospitality, Chloraka invites you to discover the heart and soul of Cyprus, making it an unforgettable destination for those seeking an immersive and memorable experience."

  },
  "Droushia": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1082-droushia_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled in the picturesque hills of Cyprus, the charming village of Droushia beckons visitors with its timeless beauty and rich cultural tapestry. Surrounded by vineyards and olive groves, Droushia offers a tranquil escape from the bustling city life, inviting guests to immerse themselves in the authentic Cypriot way of living. As you wander through its narrow cobblestone streets, you'll discover traditional stone houses adorned with vibrant bougainvillaea, creating a postcard-perfect setting. Droushia's panoramic views of the Akamas Peninsula and the sparkling Mediterranean Sea add to its allure, making it a haven for nature enthusiasts and photographers alike. The village is not only a feast for the eyes but also a treat for the taste buds, boasting a plethora of tavernas serving delectable local dishes, showcasing the island's culinary prowess. Don't miss the opportunity to sample the region's renowned wines, cultivated in the nearby vineyards, or indulge in the world-famous halloumi cheese that Cyprus is celebrated for. Beyond its scenic beauty and gastronomic delights, Droushia is steeped in history, with the Church of Agios Spiridonas standing as a testament to the village's cultural heritage. Whether you choose to explore the nearby Akamas nature reserve, embark on a hiking adventure, or simply unwind in the tranquillity of this charming village, Droushia promises an authentic Cypriot experience that will linger in your memories long after you leave."

  },
  "Giolou": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1083-giolou_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled in the picturesque landscapes of Cyprus, Giolou emerges as a hidden gem, offering visitors a tranquil escape from the bustling tourist hubs. This quaint village, situated in the Paphos district, embodies the essence of traditional Cypriot charm. Giolou's rustic allure lies in its unspoiled beauty, where vineyards stretch as far as the eye can see, and centuries-old olive trees cast a soothing shade. The village exudes a laid-back ambience, inviting wanderers to explore its narrow cobblestone streets lined with traditional stone houses adorned with vibrant bougainvillaea. A stroll through Giolou unveils its rich agricultural heritage, with locals passionately cultivating vineyards and producing some of the finest wines in the region. The aroma of freshly harvested grapes fills the air, promising a delightful sensory experience for wine enthusiasts. As the day unfolds, visitors can partake in the warm hospitality of the locals, savouring traditional Cypriot delicacies at the charming tavernas that dot the village. Beyond its culinary delights, Giolou provides a gateway to nature, with scenic hiking trails leading to panoramic views of the surrounding hills and valleys. Whether exploring the historical St. Mamas Church or simply relishing the simplicity of rural life, Giolou stands as a testament to Cyprus's timeless beauty, offering an authentic and immersive experience for those seeking a respite from the mainstream tourist destinations."

  },
  "Kallepia": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1086-kallepia_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled in the picturesque landscape of Cyprus, the charming village of Kallepia beckons visitors with its rich tapestry of history, culture, and natural beauty. Tucked away in the western part of the island, Kallepia stands as a testament to the island's timeless allure. The village is a harmonious blend of traditional Cypriot architecture and modern amenities, offering a serene escape for those seeking a taste of authentic Mediterranean life. Wander through the narrow cobblestone streets, where rustic stone houses adorned with vibrant bougainvillaea create a postcard-worthy scene at every turn. The heart of Kallepia lies in its warm and welcoming community, where locals are more than happy to share stories of generations past and present. Immerse yourself in the local culture by exploring the village's quaint coffee shops and tavernas, where the aroma of freshly brewed coffee mingles with the enticing scent of traditional Cypriot dishes. Nature enthusiasts will find solace in the surrounding vineyards and olive groves, offering a tranquil backdrop for leisurely walks and scenic picnics. For history aficionados, the nearby Chrysorrogiatissa Monastery stands as a testament to the village's spiritual heritage, dating back centuries. With its laid-back charm and a perfect blend of tradition and modernity, Kallepia invites visitors to slow down, savour the moment, and embrace the timeless beauty of Cyprus."

  },
  "Kamares Village": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1087-kamares-village_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled in the scenic hills of Paphos, Cyprus, Kamares Village beckons tourists with its captivating charm and idyllic setting. This quaint village, perched on the southwestern slopes of the Troodos Mountains, offers a serene escape from the bustling tourist hubs. Renowned for its unique architectural character, Kamares Village boasts a collection of charming villas adorned with traditional stone facades and terracotta roofs, seamlessly blending with the surrounding natural beauty. As tourists stroll through the narrow cobblestone streets, they are greeted by vibrant bougainvillaea cascading over whitewashed walls, creating a picturesque tableau. The heart of Kamares Village is its charming square, a vibrant hub where locals and visitors alike gather to savour authentic Cypriot cuisine in cosy tavernas. The panoramic views of the Mediterranean Sea from this elevated location are nothing short of breathtaking, offering a perfect backdrop for leisurely meals. Nature enthusiasts can explore the nearby Akamas Peninsula or embark on a journey through the Troodos Mountains, while history buffs will find themselves immersed in the ancient ruins of Paphos, just a short drive away. Kamares Village encapsulates the essence of Cyprus, providing a tranquil haven for those seeking an authentic and relaxing escape."

  },
  "Kathikas": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1088-kathikas_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled in the picturesque landscapes of Cyprus, the charming village of Kathikas beckons travellers with its unique blend of traditional charm and natural beauty. Tucked away in the western part of the island, Kathikas is a hidden gem that offers visitors a tranquil escape from the bustling tourist hubs. Surrounded by rolling vineyards and lush orchards, the village is renowned for its authentic Cypriot atmosphere and warm hospitality. As you wander through the narrow cobblestone streets, you'll discover traditional stone houses adorned with vibrant bougainvillaea, creating a postcard-perfect setting. Kathikas is not just a feast for the eyes; it's also a paradise for food enthusiasts. The village boasts a thriving wine culture, with numerous wineries producing some of Cyprus's finest wines. Indulge in a wine-tasting experience, savouring the rich flavours of locally produced varieties amidst the breathtaking backdrop of the Akamas Peninsula. For those seeking outdoor adventures, Kathikas serves as a gateway to the rugged beauty of the Akamas National Park, offering hiking trails that lead to hidden waterfalls and secluded beaches. Whether you're a history buff exploring the Byzantine churches scattered across the village or a nature lover captivated by the panoramic views, Kathikas promises an authentic Cypriot experience that lingers in the hearts of all who venture into its welcoming embrace."

  },
  "Kissonerga": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1089-kissonerga_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled along the sun-kissed shores of the Mediterranean, Kissonerga beckons to the adventurous traveller with its quaint charm and captivating landscapes. This idyllic coastal village, situated on the southwestern tip of Cyprus, effortlessly marries tradition with modernity, offering a delightful escape from the hustle and bustle of conventional tourist hubs. The heart of Kissonerga pulsates with a timeless rhythm, echoed in its narrow winding streets, adorned with vibrant bougainvillaea and charming stone-built houses that whisper tales of centuries gone by. For history enthusiasts, the village boasts a rich tapestry of archaeological treasures, including the fascinating Tombs of the Kings, a necropolis dating back to the 4th century BC, where visitors can wander through subterranean chambers and marvel at ancient tombs carved into the rock. Kissonerga also serves as a gateway to the Akamas Peninsula, a pristine nature reserve where crystal-clear waters meet lush landscapes, enticing hikers and nature lovers to explore its trails and discover hidden coves. The warm hospitality of the locals is matched only by the delectable offerings of the village's traditional tavernas, where the aroma of freshly caught seafood mingles with the scent of locally sourced herbs, creating a culinary symphony that tempts even the most discerning palates. As the day unfolds into the night, Kissonerga transforms into a haven for stargazers, providing an unobstructed view of the cosmos that leaves a lasting imprint on the soul. In Kissonerga, time seems to slow down, inviting visitors to savour the simplicity of life, bask in the warmth of the Cypriot sun, and create memories that linger long after the journey's end."

  },
  "Latchi": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1094-latchi_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Beyond its coastal allure, Latchi is a gateway to the Akamas Peninsula, a nature lover's paradise with rugged landscapes, hiking trails, and diverse flora and fauna. A hidden gem, Latchi beckons travellers with its irresistible blend of tranquillity and natural beauty. With its charming harbour, crystal-clear waters, and a backdrop of rolling hills, Latchi offers an escape from the bustling tourist hubs. The azure waters of Latchi Bay invite visitors to indulge in a myriad of water activities, from leisurely boat trips to exhilarating water sports. The village is renowned for its fresh seafood, and a visit to one of the waterfront tavernas is a culinary delight not to be missed. Stroll through the narrow streets lined with traditional stone houses and discover the authentic Cypriot way of life. Nature enthusiasts will find solace in the nearby Akamas Peninsula, a protected national park where hiking trails unveil breathtaking landscapes, including the renowned Baths of Aphrodite. Whether seeking relaxation on the sun-kissed beaches, savouring local delicacies, or embarking on outdoor adventures, Latchi captivates the hearts of those who yearn for an off-the-beaten-path experience in the embrace of Cyprus's coastal charm."

  },
  "Miliou": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1100-miliou_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled in the picturesque landscape of Cyprus, Miliou emerges as a hidden gem awaiting discovery by intrepid travellers. This quaint village enveloped in the lush embrace of vineyards and almond groves, captivates visitors with its serene ambiance and authentic Cypriot charm. Surrounded by the enchanting Akamas Peninsula, Miliou is a haven for nature enthusiasts, offering a tranquil retreat from the bustling tourist hubs. The village is renowned for its therapeutic springs, believed to possess healing properties, attracting wellness seekers from around the world. As you wander through the narrow, cobbled streets, you'll encounter traditional stone houses adorned with vibrant bougainvillaea, inviting you to step back in time and savour the slow pace of rural life. The Miliou region is a paradise for birdwatchers, with its diverse avian population gracing the skies above the lush countryside. Additionally, the nearby Diarizos River Valley offers scenic hiking trails that lead to breathtaking viewpoints, allowing visitors to immerse themselves in the breathtaking beauty of the Mediterranean landscape. Culinary delights await in Miliou's local tavernas, where you can indulge in authentic Cypriot dishes made from fresh, locally sourced ingredients. Whether you seek rejuvenation in the natural springs, cultural immersion in the village life, or adventure in the surrounding wilderness, Miliou promises an idyllic escape for those seeking an authentic and tranquil Cyprus experience."

  },
  "Nea Dimmata": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1101-nea-dimmata_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled on the rugged northwestern coast of Cyprus, Nea Dimmata beckons intrepid travellers with its unspoiled charm and captivating landscapes. This quaint village, steeped in history and surrounded by the azure waters of the Mediterranean, offers a tranquil retreat away from the bustling tourist hubs. The heart of Nea Dimmata pulsates with the warmth of traditional Cypriot hospitality, as locals welcome visitors with genuine smiles and open arms. Wander through the narrow, cobblestone streets lined with whitewashed houses adorned with vibrant bougainvillaea, immersing yourself in the authentic Mediterranean atmosphere. The village's main focal point is the picturesque fishing harbour, where colourful boats bob gently in the breeze, and waterfront tavernas tempt you with the tantalizing aroma of freshly caught seafood. Nature enthusiasts will find solace in the untamed beauty of the surrounding countryside, with hiking trails leading to breathtaking viewpoints overlooking the crystal-clear waters below. Nea Dimmata, with its rich tapestry of culture, stunning vistas, and a palpable sense of tranquillity, invites travellers to experience the Cyprus of yesteryear, where time seems to slow down, and every moment is savoured like a fine glass of local wine."

  },
  "Neo Chorio": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1102-neo-chorio_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled on the northwestern coast of Cyprus, Neo Chorio beckons travellers with its enchanting blend of traditional charm and breathtaking natural beauty. A quaint village with a rich history, Neo Chorio offers a serene escape from the bustling tourist hubs, providing an authentic Cypriot experience. The heart of the village boasts narrow cobblestone streets lined with traditional stone houses adorned with vibrant bougainvillaea, creating a picturesque setting that invites exploration. A highlight for nature enthusiasts is the proximity to the Akamas Peninsula, a pristine nature reserve teeming with diverse flora and fauna. Adventurous souls can embark on hiking trails that lead to stunning viewpoints, revealing panoramic vistas of the rugged coastline and crystal-clear waters of the Mediterranean Sea. For those seeking relaxation, the nearby Baths of Aphrodite, shrouded in myth and legend, offer a tranquil oasis surrounded by lush greenery. Neo Chorio's welcoming atmosphere extends to its local tavernas, where visitors can savour authentic Cypriot cuisine, from freshly caught seafood to savoury meze platters, all accompanied by the warmth of traditional hospitality. Whether strolling through the historic village centre, exploring the untamed beauty of Akamas, or indulging in the local flavours, Neo Chorio unfolds as a hidden gem for those seeking an off-the-beaten-path experience on the sun-kissed island of Cyprus."

  },
  "Peristerona": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1103-peristerona_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled in the scenic landscape of Cyprus, the charming village of Peristerona beckons travellers with its rich history and picturesque surroundings. Steeped in tradition, this hidden gem is a testament to the island's cultural heritage. As you wander through its narrow cobblestone streets, you'll encounter traditional Cypriot architecture, with quaint stone houses adorned with vibrant bougainvillaea and geraniums. The heart of Peristerona is its central square, where locals gather in the shade of ancient olive trees, creating a warm and inviting atmosphere. Don't miss the opportunity to explore the historic Church of Archangel Michael, a beautifully preserved Byzantine church dating back to the 16th century, showcasing intricate frescoes that tell tales of centuries gone by. For those seeking a deeper connection to the village's agricultural roots, the surrounding countryside offers a patchwork of olive groves and vineyards, inviting visitors to indulge in the flavours of local produce and wines. Peristerona encapsulates the essence of a tranquil Cypriot village, providing a serene escape for travellers seeking authenticity and a genuine connection to the island's past."

  },
  "Peyia": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1105-peyia_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled on the picturesque slopes of the western Cyprus coastline, Peyia emerges as a captivating haven for tourists seeking a harmonious blend of cultural richness and natural beauty. Perched above the azure waters of the Mediterranean, this charming village offers a mesmerizing panorama of the sea and the rugged coastline. Visitors to Peyia are greeted by a tapestry of traditional stone houses, narrow winding streets, and vibrant bougainvillaea, creating an idyllic Mediterranean ambience. The heart of the village pulsates with a sense of history, as ancient churches and cultural landmarks weave tales of a bygone era. A visit to the iconic Church of the Virgin Mary, with its timeless architecture and serene surroundings, provides a spiritual retreat and a glimpse into the island's cultural heritage. For those with an adventurous spirit, the Akamas Peninsula beckons, showcasing untamed landscapes and rare flora and fauna. The renowned Sea Caves, carved by the relentless waves over centuries, stand as a testament to nature's sculptural prowess. As the sun dips below the horizon, casting a golden hue over the landscape, Peyia transforms into a romantic retreat with its array of traditional tavernas and cosy cafes, offering delectable Cypriot cuisine and warm hospitality. Whether exploring the ancient charm of the village, embarking on a nature trek through the Akamas, or savouring the sunset by the sea, Peyia invites travellers to immerse themselves in the enchanting tapestry of Cyprus's cultural and natural wonders."

  },
  "Limni": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1106-limni_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled on the picturesque shores of Cyprus, Limni emerges as a hidden gem, enchanting visitors with its unique blend of history, culture, and natural beauty. This coastal town, situated on the island's western edge, beckons travellers with its tranquil ambience and a rich tapestry of experiences. Limni is renowned for its pristine beaches, where golden sands meet the crystal-clear waters of the Mediterranean Sea, offering a perfect retreat for sun-seekers and water enthusiasts alike. Beyond the coastline, Limni invites exploration of its charming cobblestone streets adorned with traditional Cypriot architecture, creating a captivating atmosphere that harks back to centuries past. The town's historic landmarks, such as the medieval Limnia Tower and the 16th-century Church of Panagia, provide a fascinating journey through time, offering glimpses into the island's storied past. As the sun sets, Limni transforms into a culinary haven, with its waterfront tavernas serving up delectable seafood dishes, allowing visitors to savour the flavours of Cyprus while enjoying a mesmerizing view of the sunset. Limni, with its harmonious blend of nature, history, and gastronomy, promises an unforgettable experience for those seeking an authentic and idyllic retreat on this enchanting Mediterranean island."

  },
  "Polis": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1107-polis_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled on the northwest coast of Cyprus, Polis is a captivating gem that beckons travellers with its unspoiled beauty and authentic charm. Framed by the azure waters of the Mediterranean Sea and the rugged landscapes of the Akamas Peninsula, Polis offers a tranquil escape from the bustling tourist hubs. A stroll through the town's cobbled streets reveals a delightful blend of traditional Cypriot architecture, quaint cafes, and inviting tavernas where visitors can savour local delicacies. The focal point of Polis is the enchanting town square, surrounded by citrus groves and overlooked by the imposing facade of the 18th-century Panagia Chryseleousa Church. Nature enthusiasts are drawn to the area's pristine beaches, including the renowned Latchi Beach, where crystalline waters meet golden sands, and the Akamas National Park, a haven for hikers and wildlife enthusiasts alike. Adventure-seekers can embark on boat trips from the picturesque Latchi Harbor, exploring hidden coves and the mythical Baths of Aphrodite. With its laid-back atmosphere and proximity to natural wonders, Polis beckons those seeking an authentic and rejuvenating Cypriot experience."

  },
  "Sea Caves": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1113-sea-caves_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled along the rugged coastline of Cyprus, the Sea Caves stand as a mesmerizing natural wonder, enticing tourists with their breathtaking beauty and geological intrigue. Carved over centuries by the relentless embrace of the Mediterranean Sea, these enchanting caves offer a captivating glimpse into the island's geological history. Located near the resort town of Paphos, the Sea Caves boast a unique charm characterized by limestone formations, hidden grottoes, and crystal-clear azure waters. Adventurous visitors can explore the labyrinthine caves by boat or, for the more intrepid, take a refreshing swim in the invigorating waters surrounding these geological marvels. The dramatic interplay of light and shadow within the caves creates a photographer's paradise, with every angle revealing a new perspective of nature's artistry. Beyond their aesthetic appeal, the Sea Caves also hold a mystique, with local legends whispering tales of pirates and hidden treasures that add a touch of allure to the already magical atmosphere. As the sun sets, casting a warm golden glow upon the cliffs, the Sea Caves transform into a romantic haven, making it an ideal spot for couples seeking a serene and picturesque escape. Whether you're an avid nature enthusiast, a history buff, or simply in search of a tranquil retreat, the Sea Caves of Cyprus promise an unforgettable experience, leaving visitors enchanted by the raw beauty etched into the island's coastal landscape."

  },
  "Skoulli": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1115-skoulli_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled in the scenic embrace of Cyprus, the quaint village of Skoulli beckons to discerning travellers seeking an authentic and tranquil escape. Situated in the western part of the island, Skoulli is a hidden gem surrounded by the captivating landscapes of the Paphos region. As you traverse its cobbled streets, you'll find yourself immersed in the rich tapestry of Cypriot culture and history. The village, adorned with traditional stone houses and fragrant vineyards, exudes an old-world charm that transports visitors back in time. Skoulli is renowned for its welcoming locals, who take pride in preserving the area's cultural heritage. A stroll through the village reveals the remnants of ancient structures, including a historic church that stands as a testament to the enduring spirit of the community. Nature enthusiasts will delight in the proximity of Skoulli to the Akamas Peninsula, a pristine nature reserve offering a breathtaking mosaic of landscapes, from rugged cliffs to lush forests. Adventure seekers can embark on hiking trails that unveil the region's diverse flora and fauna, while those yearning for tranquillity can indulge in the serene beauty of the nearby Avakas Gorge. Culinary enthusiasts will savour the authentic tastes of Cyprus at Skoulli's traditional tavernas, where locally sourced ingredients elevate the dining experience. Whether exploring the village's historical sites, embarking on outdoor adventures, or simply relishing the unhurried pace of life, Skoulli invites visitors to immerse themselves in the soul-stirring allure of Cyprus's western wonders."

  },
  "Stroumbi": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1118-stroumbi_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled in the picturesque landscape of Cyprus, Stroumbi beckons to the discerning traveller with its charm and tranquillity. This quaint village, situated in the western part of the island, offers a delightful escape from the bustling tourist hubs, providing an authentic taste of Cypriot life. As you meander through Stroumbi's narrow cobblestone streets, adorned with vibrant bougainvillaea, you'll find yourself immersed in a rich tapestry of local culture. The heart of the village is its central square, a gathering place where locals and visitors alike congregate to savour traditional Cypriot cuisine in welcoming tavernas. The aroma of freshly baked bread and the melodic notes of live music create an ambience that is both inviting and evocative of the island's warm hospitality. Stroumbi is not only a haven for those seeking a slower pace but also a gateway to the region's natural wonders. Surrounded by rolling vineyards and orchards, the area is renowned for its wine production, offering wine enthusiasts a chance to indulge in tastings at local wineries. The more adventurous can explore the nearby Akamas Peninsula, where rugged landscapes, hidden coves, and ancient ruins await discovery. Whether you are drawn to Stroumbi for its idyllic setting, cultural richness, or outdoor adventures, this hidden gem promises a truly immersive and unforgettable experience for those willing to venture off the beaten path in Cyprus."

  },
  "Tala": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1119-tala_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled in the picturesque hills of Cyprus, Tala beckons to tourists with its charm and rich cultural tapestry. At the heart of this quaint village lies Tala Square, a bustling hub where locals and visitors alike converge to savour the authentic Cypriot atmosphere. The square is a sensory delight, with traditional tavernas serving mouthwatering local delicacies and quaint shops offering handmade crafts, providing a perfect blend of gastronomy and cultural exploration. A short stroll away unveils the Amphitheatre, an ancient gem that transports visitors back in time. This historical site not only showcases the architectural prowess of the ancient Greeks but also serves as a venue for cultural events and performances, creating an immersive experience for those eager to delve into the island's rich history. Further up the hills, the Ayios Neofytos Monastery stands as a testament to Cyprus's spiritual heritage. Founded in the 12th century by Neofytos, a hermit and writer, the monastery boasts captivating frescoes depicting scenes from the Bible and the life of its founder. The serene surroundings and the monastery's historical significance make it a must-visit destination for those seeking a tranquil retreat infused with cultural depth. Tala, with its Tale Square, the Amphitheatre, and the Ayios Neofytos Monastery, offers a kaleidoscopic journey through Cyprus's vibrant past and present, inviting tourists to savor every moment of their exploration."

  },
  "Pomos": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/115764-pomos_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled along the picturesque coastline of Cyprus, Pomos beckons travellers with its charm and unspoiled beauty. This idyllic village, situated on the northwest side of the island, is a hidden gem that promises an authentic Cypriot experience. Framed by the azure waters of the Mediterranean Sea and the rugged backdrop of the Troodos Mountains, Pomos captivates visitors with its breathtaking landscapes. The village is renowned for its tranquil atmosphere and traditional character, offering a serene escape from the hustle and bustle of more touristy destinations. Wander through narrow cobblestone streets lined with quaint houses adorned with vibrant bougainvillaea, and you'll find a community that has preserved its cultural heritage with pride. The heart of Pomos lies in its charming fishing harbour, where colourful boats bob gently in crystal-clear waters. Seafood enthusiasts will delight in the local tavernas, serving up freshly caught delights accompanied by warm Cypriot hospitality. For those seeking adventure, the Akamas Peninsula, a rugged and wild nature reserve, is within easy reach, offering hiking trails that lead to hidden coves and panoramic viewpoints. Whether you're drawn to Pomos for its natural beauty, cultural richness, or the allure of its tranquil shores, this unassuming village promises an authentic and unforgettable experience for every traveller."

  },
  "Theletra": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/195898-theletra_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled in the picturesque landscape of Cyprus, Theletra unfolds as a hidden gem, inviting intrepid travellers to immerse themselves in the rich tapestry of Cypriot history and natural beauty. This quaint village, with its charming stone houses and narrow winding streets, exudes a timeless charm that transports visitors to a bygone era. Theletra boasts a captivating blend of tradition and tranquillity, offering a respite from the bustling tourist hubs. Stroll through the village, where vibrant bougainvillaea cascades over white-washed walls, creating a stunning contrast against the azure sky. Theletra is renowned for its warm hospitality, with locals eager to share stories of their heritage and customs. Explore the Byzantine church of Panagia Chrysokourdaliotissa, adorned with intricate frescoes that narrate tales of faith and artistry. For nature enthusiasts, the surrounding countryside unveils hiking trails that lead to breathtaking vistas of the Troodos Mountains, rewarding hikers with panoramic views of the island's diverse topography. In the heart of Theletra, traditional tavernas beckon with the aroma of authentic Cypriot cuisine, a tantalizing blend of Mediterranean flavours that reflect the village's agricultural abundance. As the sun sets over this idyllic enclave, casting a golden glow on the landscape, visitors to Theletra find themselves enchanted by the simplicity and authenticity that define this off-the-beaten-path destination."

  },
  "Agios Theodoros": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/197593-agios-theodoros_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled on the southern coast of Cyprus, the charming village of Agios Theodoros beckons tourists with its unique blend of tradition and tranquillity. Set against a backdrop of rolling hills and the azure waters of the Mediterranean, this idyllic haven offers a serene escape from the bustling tourist hubs. Steeped in history, Agios Theodoros boasts ancient stone houses adorned with vibrant bougainvillaea, a testament to the village's rich cultural heritage. Strolling through its narrow cobblestone streets, visitors can immerse themselves in the authentic Cypriot way of life, where time seems to slow down. The heart of the village is its picturesque square, surrounded by quaint cafes and tavernas serving delicious local cuisine. Don't miss the opportunity to savour traditional dishes such as souvlaki and moussaka while soaking in the warm hospitality of the locals. Agios Theodoros is also renowned for its beautiful beaches, where golden sands meet crystal-clear waters, providing a perfect setting for relaxation and rejuvenation. Nature enthusiasts can explore the nearby wetlands, a haven for birdwatching and a sanctuary for diverse wildlife. Whether you seek a peaceful retreat or a cultural adventure, Agios Theodoros invites you to experience the authentic allure of Cyprus, where ancient charm meets modern serenity."

  },
  "Pyla": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/197939-pyla_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled on the eastern coast of Cyprus, the charming village of Pyla beckons travellers with its unique blend of history, culture, and natural beauty. Renowned for being the only village on the island where Greek and Turkish Cypriots coexist harmoniously, Pyla offers a fascinating glimpse into the complex tapestry of Cyprus's multicultural heritage. Wander through the narrow cobblestone streets, and you'll encounter a harmonious mosaic of architectural influences, from traditional Cypriot houses to Ottoman-era structures, reflecting the village's rich past. History enthusiasts can explore the Pyla-Kokkinokremos archaeological site, an ancient settlement that dates back to the Late Bronze Age, providing insights into the island's prehistoric period. Nature lovers, on the other hand, can bask in the sun at the nearby Pyla Beach, with its golden sands and crystal-clear waters offering a serene escape. As the sun sets, immerse yourself in the local dining scene, where a plethora of restaurants serves up a delectable fusion of Greek and Turkish cuisines, showcasing the unique culinary heritage of Pyla. Whether you're strolling through its historical streets, relaxing on its sun-soaked beaches, or savouring its diverse flavours, Pyla invites you to embrace the captivating essence of Cyprus's cultural diversity in a single, picturesque setting."

  },
  "Ayia Triada": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/198771-ayia-triada_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled on the southeastern coast of Cyprus, Ayia Triada is a hidden gem awaiting discovery by avid travellers seeking a perfect blend of history, tranquillity, and coastal beauty. This charming locality, just a stone's throw away from the bustling resort town of Protaras, boasts a rich historical tapestry and a serene ambience that beckons visitors to immerse themselves in its unique allure. At the heart of Ayia Triada lies the eponymous archaeological site, a treasure trove of ancient ruins dating back to the Hellenistic period. Wander among the remnants of a once-vibrant ancient city, marvelling at the well-preserved structures, including a stunning complex of Roman villas adorned with intricate mosaics. The site's proximity to the azure waters of the Mediterranean Sea adds an extra layer of allure, providing a picturesque backdrop that beautifully contrasts with the historical remnants. Beyond its archaeological wonders, Ayia Triada offers pristine beaches where visitors can unwind and bask in the Mediterranean sun. With its crystal-clear waters and golden sands, the beaches of Ayia Triada provide an idyllic setting for relaxation and water-based activities. Local tavernas and eateries dot the coastline, tempting visitors with delicious Cypriot cuisine and fresh seafood. As the sun dips below the horizon, casting a warm glow over the landscape, Ayia Triada transforms into a magical destination that captivates the hearts of all who venture here, leaving an indelible mark on the memories of those fortunate enough to experience its unique charm."

  },
  "Tremithousa": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/277753-tremithousa_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled in the picturesque landscape of Cyprus, Tremithousa beckons with its charm and historical allure, making it a captivating destination for discerning tourists. This quaint village, situated just a stone's throw away from the bustling city of Paphos, offers a unique blend of traditional Cypriot culture and modern comforts. The heart of Tremithousa is its charming town square, where narrow cobblestone streets wind their way through traditional houses adorned with vibrant bougainvillaea, creating a postcard-perfect setting. As you explore the village, you'll encounter friendly locals who are eager to share stories of their rich heritage. Tremithousa is renowned for its well-preserved architecture, with many buildings dating back centuries, providing a fascinating glimpse into the island's history. For nature enthusiasts, the surrounding hills and valleys offer breathtaking vistas and scenic trails, perfect for a leisurely hike or a quiet escape. Additionally, Tremithousa boasts a vibrant culinary scene, with charming tavernas serving authentic Cypriot dishes that tantalize the taste buds. Visitors can indulge in the flavours of local delicacies while savouring the warm hospitality that characterizes the village. Whether you're seeking cultural immersion, natural beauty, or culinary delights, Tremithousa promises an enriching and delightful experience that lingers in the memory long after your visit to this hidden gem on the sun-kissed island of Cyprus."

  },
  "Lysos": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/1395021-lysos_orig%20copy.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled in the picturesque landscape of Cyprus, the charming village of Lysos beckons travellers with its idyllic setting and rich cultural tapestry. Located in the northwestern part of the island, Lysos is a hidden gem that offers a tranquil retreat from the bustling tourist hubs. Surrounded by lush greenery and rolling hills, this traditional Cypriot village captivates visitors with its authentic charm and warm hospitality. Stroll through the cobblestone streets lined with stone-built houses adorned with vibrant bougainvillaea, immersing yourself in the timeless beauty of this rural enclave. Lysos is not just a feast for the eyes; it also provides a gateway to the Akamas Peninsula, a pristine natural reserve known for its diverse flora and fauna. Nature enthusiasts can embark on scenic hikes or jeep safaris, exploring the untamed wilderness and enjoying breathtaking views of the Mediterranean Sea. The village itself boasts a rich history, evident in its well-preserved churches and cultural landmarks. The 16th-century church of Agios Andronikos and the Folk Art Museum offer glimpses into the region's past, showcasing the artistry and traditions of its people. To savour the authentic flavours of Cyprus, indulge in local cuisine at one of Lysos' traditional tavernas, where you can relish mouthwatering dishes prepared with fresh, locally sourced ingredients. Whether you seek a peaceful escape into nature, a cultural journey through history, or simply a delightful culinary experience, Lysos promises a captivating and rejuvenating retreat for the discerning traveller."

  },
  "Akoursos": {
    "imageSrc": "https://dl.dropboxusercontent.com/scl/fo/y4dfklpyy2w4tybicnsxl/h/akoursos.webp?rlkey=ecb972vzouyom5da27xi39rcr&dl=0",
"description": "Nestled amidst the undulating landscapes of Cyprus, the quaint village of Akoursos beckons travellers with its charm and serenity. Tucked away in the western part of the island, Akoursos offers a tranquil escape from the bustling tourist hubs, providing visitors with an authentic taste of Cypriot village life. Surrounded by lush greenery and commanding panoramic views of the Mediterranean Sea, this idyllic hamlet captivates with its traditional stone houses adorned with vibrant bougainvillaea, creating a picturesque setting for exploration. Wander through the narrow, winding streets that weave through the village, discovering hidden gems like local tavernas where the tantalizing aroma of freshly prepared Mediterranean cuisine wafts through the air. Akoursos is not only a visual delight but also a haven for nature enthusiasts, as it provides easy access to hiking trails that wind through the scenic countryside. A visit to the nearby Akoursos Dam offers a peaceful retreat, allowing travellers to bask in the beauty of the natural surroundings. As the sun sets over Akoursos, casting a warm glow on the landscape, visitors can relish the tranquillity of this charming village, making it a truly memorable stop on their journey through Cyprus."

  }
};





    // Function to update the description in the HTML
function updateDescription(locationText) {
  const description = document.querySelector('.description');

  if (locationData[locationText] && description) {
    description.textContent = locationData[locationText].description;
  }
}

// Function to set the URL for the "Read More" button
function setButtonURL(locationText) {
  const descriptionButton = document.querySelector('.description-button');

  const hyphenatedText = locationText.replace(/\s+/g, '-'); // Replace spaces with hyphens
  const url = '/locations/' + hyphenatedText.toLowerCase(); // Convert to lowercase

  descriptionButton.addEventListener('click', () => {
  window.location.href = url; // Redirect the user to the URL
}, { passive: true });
}

// Function to set the image for the .location-image div
function setLocationImage(locationText) {
  const locationImageData = locationData[locationText];
  const locationImageDiv = document.querySelector('.location-image');

  if (locationImageData && locationImageDiv) {
    const locationImage = new Image();
    locationImage.src = locationImageData.imageSrc;
    locationImage.alt = locationText; // You can set an alt attribute for accessibility

    // Set the image to 100% width and height
    locationImage.style.width = '100%';
    locationImage.style.height = '100%';

    // Replace the content of the .location-image div with the image
    locationImageDiv.innerHTML = '';
    locationImageDiv.appendChild(locationImage);
  }
}

// Callback function for MutationObserver
function handleMutation(mutationsList) {
  const villaLocation = document.querySelector('.villa-location');
  const locationText = villaLocation.textContent.trim();

  setButtonURL(locationText);
  setLocationImage(locationText);
  updateDescription(locationText);
}

// Wait for the villa location text to be populated and then call the functions using MutationObserver
window.addEventListener('DOMContentLoaded', () => {
  const villaLocation = document.querySelector('.villa-location');

  // Create a MutationObserver instance
  const observer = new MutationObserver(handleMutation);

  // Configure the observer to watch for changes in the subtree
  const observerConfig = { subtree: true, childList: true };

  // Start observing the target node for configured mutations
  observer.observe(villaLocation, observerConfig);

  // Initial call to set the URL, set the image, and update the description
  const locationText = villaLocation.textContent.trim();
  setButtonURL(locationText);
  setLocationImage(locationText);
  updateDescription(locationText);
});
